### ISSUE TITLE
Crashes on MRS and MSR instructions

### ISSUE THREAD

**Issue by mateusz-banaszek** [valour01/examiner#1]
When launching the `generate_insts_from_asl()` function of `instrs2asl.py`, the tool crashes on MRS and MSR instructions:

```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/XXX/mra_tools/bin/instrs2asl.py", line 981, in generate_insts
    for condition in self.conditions:
  File "/XXX/mra_tools/bin/instrs2asl.py", line 1137, in solve
  File "<string>", line 1
    SYSm == SYSm<0>
SyntaxError: invalid syntax
```

**Comment by msuadOf** [comment]
how can you run it？it seems that there is some missing files to use codes at `diff-engine/angr-unicorn/`.

**Comment by mateusz-banaszek** [comment]
> how can you run it？it seems that there is some missing files to use codes at `diff-engine/angr-unicorn/`.

I only tried to run the `test-generator` part. I didn't try to run anything from `diff-engine`.

**Comment by msuadOf** [comment]
but `test-generator` seems to be used to generate the ASL. I want to gen the testcase like how the paper describes, too.

**Comment by mateusz-banaszek** [comment]
It was a long time ago, so I don't remember all the details, but I managed to generate some test cases by combining `test-generator` with https://github.com/alastairreid/mra_tools and then by modifying them to work around problems I had (see other Issues submitted by me). I did it by trial and error, and if I recall correctly, it generated for me fewer cases than the paper describes.

**Comment by msuadOf** [comment]
ok. can  you  tell which  file you used to gen  the  testcase file?

**Comment by mateusz-banaszek** [comment]
My notes say that I basically followed the mra_tools's ReadMe but used `instrs2asl.py` from this repo, and then I launched `bin/instrs2asl.py` to generate test cases.

**Comment by msuadOf** [comment]
wait,where is `bin` folder?

**Comment by msuadOf** [comment]
is the mra_tools's one? and is there some simple example commands to start up my exloration?

**Comment by mateusz-banaszek** [comment]
Yes. I run something like `bin/instrs2asl.py --arch AArch32 -oarch/arch v8.6/ISA_AArch32_xml_v86A-2019-12`, but I'm not sure what parameters to use to generate the test cases described in the paper.

**Comment by msuadOf** [comment]
ok, thank you anyway.i maybe need to read more source code to understand it...
